import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Provider } from 'react-redux'
import GLOBAL_STORE from '../src/redux/store'
import MainScreen from '../src/components/MainScreen'

export default function Home() {
  return (
    <Provider store={GLOBAL_STORE}>
      <div className={styles.container}>
        <Head>
          <title>Chat App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <MainScreen />
    </Provider>
  )
}
